nelmio_cors:
    defaults:
        allow_credentials: true
        # Décommenter pour utiliser les origines intégrées en dur, sans le .env
        #        allow_origin:
        #            [
        #                "http://localhost:5173",
        #                "https://nutrition-app-steel.vercel.app",
        #                "https://nutrition-app-steel-preprod.vercel.app",
        #            ]
        origin_regex: true
        allow_origin: ["%env(string:CORS_ALLOW_ORIGIN)%"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link", "Authorization"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        max_age: 3600
    paths:
        "^/api/": ~
