nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ["http://localhost:5173", "http://localhost:3000"]
        allow_origin_regex:
            - '^https://nutrition-app(-[a-z0-9-]+)?\.vercel\.app$'
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link", "Authorization"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        max_age: 3600
    paths:
        "^/api/":
            allow_origin: ["http://localhost:5173", "http://localhost:3000"]
            allow_origin_regex:
                - '^https://nutrition-app(-[a-z0-9-]+)?\.vercel\.app$'
            allow_headers: ["Content-Type", "Authorization"]
            expose_headers: ["Link", "Authorization"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            max_age: 3600
