nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ["http://localhost:5173", "http://localhost:5174"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link", "Authorization"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        max_age: 3600
    paths:
        "^/api/":
            allow_origin: ["http://localhost:5173", "http://localhost:5174"]
            allow_headers: ["Content-Type", "Authorization"]
            expose_headers: ["Link", "Authorization"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            max_age: 3600
