name: Deploy Symfony API to Alwaysdata

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ALWAYSDATA_HOST }} >> ~/.ssh/known_hosts

      - name: Push backend to Alwaysdata
        run: |
          cd backend
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from GitHub Actions"
          git branch -m main
          git remote add alwaysdata ssh://adrienbaptiste@${{ secrets.ALWAYSDATA_HOST }}:${{ secrets.ALWAYSDATA_REPO }}
          git push --force alwaysdata main
