name: Deploy Symfony API to Alwaysdata

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install backend dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist

      - name: Run backend tests (PHPUnit)
        working-directory: backend
        run: |
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit --testdox
          else
            echo "PHPUnit not installed; skipping tests"
          fi

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ALWAYSDATA_HOST }} >> ~/.ssh/known_hosts

      - name: Push backend to Alwaysdata
        run: |
          cd backend
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from GitHub Actions"
          git branch -m main
          git remote add alwaysdata ssh://adrienbaptiste@${{ secrets.ALWAYSDATA_HOST }}:${{ secrets.ALWAYSDATA_REPO }}
          git push --force alwaysdata main
