name: Build & Push Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (frontend)
        run: npm ci
        working-directory: frontend

      - name: Run frontend tests (Vitest)
        run: npm run test -- --run
        working-directory: frontend

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nutrition-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/nutrition-frontend:latest
